package stopwatch;

/**
 *
 * @author Raitis
 * Class embodying the panel on which the componets of the stopwatch UI sit.
 * Components of the panel set up using drag and drop in Netbeans
 */
public class StopwatchPanel3 extends javax.swing.JPanel {

    /**
     * Creates new form StopwatchPanel3
     * and registers inner classes of 
     * the StopwatchController as listener for the buttons.
     * @param controller the StopwatchController instance containing inner classes
     * that act as listeners for the button.
     */
    public StopwatchPanel3(StopwatchController controller) {
        initComponents(); // execute initial code generated by drag and drop
        startButton.addActionListener(controller.new StartActionListener());
        stopButton.addActionListener(controller.new StopActionListener());
        resetButton.addActionListener(controller.new ResetActionListener());
        
    }
    /**
     * Sets the appropriate sensitivities for the buttons for the stopwatch.
     * @param startEnabled Starts button enabled/disabled
     * @param stopEnabled Stop button enabled/disabled
     * @param resetEnabled Reset button enabled/disabled
     */
    public void setButtons (boolean startEnabled, boolean stopEnabled,
            boolean resetEnabled){
        startButton.setEnabled(startEnabled);
        stopButton.setEnabled(stopEnabled);
        resetButton.setEnabled(resetEnabled);
        
    }
    
    /**
     * passes the time on the label to display it
     * @param time 
     */
    public void setTime(String time){
        timerLabel.setText(time);
            }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        timerLabel = new javax.swing.JLabel();

        startButton.setText("Start");

        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(startButton)
                        .addGap(43, 43, 43)
                        .addComponent(stopButton)
                        .addGap(40, 40, 40)
                        .addComponent(resetButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(timerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stopButton)
                    .addComponent(resetButton)
                    .addComponent(startButton))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stopButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton resetButton;
    private javax.swing.JButton startButton;
    private javax.swing.JButton stopButton;
    private javax.swing.JLabel timerLabel;
    // End of variables declaration//GEN-END:variables
}
